--- Creat By...: Giovani Pacheco
--- Version....: 1.0
--- Create Date: 11/12/2022
--- Updates....:


---------------------------------------------------------------------------------------------------------
-- Table: COUNTRIES
---------------------------------------------------------------------------------------------------------


CREATE TABLE LOC.COUNTRIES (
	COUNTRY_ID		INT NOT NULL,
	COUNTRY			VARCHAR2(250) NOT NULL,
	ISO_ALPHA_CODE		VARCHAR2(3) NOT NULL,
	CONTINENT_ID		INT,
	REGION_ID		INT
);

--- CONSTRAINTS
ALTER TABLE LOC.COUNTRIES
	ADD CONSTRAINT PK001_COUNTRIES PRIMARY KEY (COUNTRY_ID);

ALTER TABLE LOC.COUNTRIES
	ADD CONSTRAINT FK001_COUNTRIES_TO_REGION FOREIGN KEY (REGION_ID) REFERENCES LOC.REGIONS (REGION_ID);

ALTER TABLE LOC.COUNTRIES
	ADD CONSTRAINT FK002_COUNTRIES_TO_CONTINENTS FOREIGN KEY (REGION_ID) REFERENCES LOC.CONTINENTS (CONTINENT_ID);
	
	
---------------------------------------------------------------------------------------------------------
-- DML: COUNTRIES 
---------------------------------------------------------------------------------------------------------

-- AFRICA
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (100,'Algeria','DZA',10,1000);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (101,'Egypt','EGY',10,1000);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (102,'Libya','LBY',10,1000);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (103,'Morocco','MAR',10,1000);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (104,'Sudan','SDN',10,1000);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (105,'Tunisia','TUN',10,1000);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (106,'Western Sahara','ESH',10,1000);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (107,'British Indian Ocean Territory','IOT',10,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (108,'Burundi','BDI',10,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (109,'Comoros','COM',10,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (110,'Djibouti','DJI',10,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (111,'Eritrea','ERI',10,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (112,'Ethiopia','ETH',10,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (113,'French Southern Territories','ATF',10,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (114,'Kenya','KEN',10,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (115,'Madagascar','MDG',10,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (116,'Malawi','MWI',10,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (117,'Mauritius','MUS',10,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (118,'Mayotte','MYT',10,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (119,'Mozambique','MOZ',10,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (120,'Réunion','REU',10,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (121,'Rwanda','RWA',10,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (122,'Seychelles','SYC',10,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (123,'Somalia','SOM',10,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (124,'South Sudan','SSD',10,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (125,'Uganda','UGA',10,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (126,'United Republic of Tanzania','TZA',10,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (127,'Zambia','ZMB',10,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (128,'Zimbabwe','ZWE',10,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (129,'Angola','AGO',10,1002);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (130,'Cameroon','CMR',10,1002);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (131,'Central African Republic','CAF',10,1002);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (132,'Chad','TCD',10,1002);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (133,'Congo','COG',10,1002);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (134,'Democratic Republic of the Congo','COD',10,1002);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (135,'Equatorial Guinea','GNQ',10,1002);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (136,'Gabon','GAB',10,1002);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (137,'Sao Tome and Principe','STP',10,1002);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (138,'Botswana','BWA',10,1003);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (139,'Eswatini','SWZ',10,1003);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (140,'Lesotho','LSO',10,1003);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (141,'Namibia','NAM',10,1003);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (142,'South Africa','ZAF',10,1003);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (143,'Benin','BEN',10,1004);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (144,'Burkina Faso','BFA',10,1004);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (145,'Cabo Verde','CPV',10,1004);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (146,'Côte d’Ivoire','CIV',10,1004);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (147,'Gambia','GMB',10,1004);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (148,'Ghana','GHA',10,1004);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (149,'Guinea','GIN',10,1004);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (150,'Guinea-Bissau','GNB',10,1004);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (151,'Liberia','LBR',10,1004);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (152,'Mali','MLI',10,1004);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (153,'Mauritania','MRT',10,1004);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (154,'Niger','NER',10,1004);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (155,'Nigeria','NGA',10,1004);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (156,'Saint Helena','SHN',10,1004);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (157,'Senegal','SEN',10,1004);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (158,'Sierra Leone','SLE',10,1004);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (159,'Togo','TGO',10,1004);

-- AMERICAS
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (160,'Anguilla','AIA',20,1005);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (161,'Antigua and Barbuda','ATG',20,1005);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (162,'Aruba','ABW',20,1005);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (163,'Bahamas','BHS',20,1005);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (164,'Barbados','BRB',20,1005);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (165,'Bonaire, Sint Eustatius and Saba','BES',20,1005);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (166,'British Virgin Islands','VGB',20,1005);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (167,'Cayman Islands','CYM',20,1005);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (168,'Cuba','CUB',20,1005);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (169,'Curaçao','CUW',20,1005);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (170,'Dominica','DMA',20,1005);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (171,'Dominican Republic','DOM',20,1005);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (172,'Grenada','GRD',20,1005);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (173,'Guadeloupe','GLP',20,1005);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (174,'Haiti','HTI',20,1005);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (175,'Jamaica','JAM',20,1005);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (176,'Martinique','MTQ',20,1005);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (177,'Montserrat','MSR',20,1005);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (178,'Puerto Rico','PRI',20,1005);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (179,'Saint Barthélemy','BLM',20,1005);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (180,'Saint Kitts and Nevis','KNA',20,1005);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (181,'Saint Lucia','LCA',20,1005);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (182,'Saint Martin (French Part)','MAF',20,1005);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (183,'Saint Vincent and the Grenadines','VCT',20,1005);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (184,'Sint Maarten (Dutch part)','SXM',20,1005);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (185,'Trinidad and Tobago','TTO',20,1005);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (186,'Turks and Caicos Islands','TCA',20,1005);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (187,'United States Virgin Islands','VIR',20,1005);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (188,'Belize','BLZ',20,1006);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (189,'Costa Rica','CRI',20,1006);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (190,'El Salvador','SLV',20,1006);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (191,'Guatemala','GTM',20,1006);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (192,'Honduras','HND',20,1006);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (193,'Mexico','MEX',20,1006);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (194,'Nicaragua','NIC',20,1006);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (195,'Panama','PAN',20,1006);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (196,'Argentina','ARG',20,1007);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (197,'Bolivia (Plurinational State of)','BOL',20,1007);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (198,'Bouvet Island','BVT',20,1007);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (199,'Brazil','BRA',20,1007);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (200,'Chile','CHL',20,1007);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (201,'Colombia','COL',20,1007);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (202,'Ecuador','ECU',20,1007);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (203,'Falkland Islands (Malvinas)','FLK',20,1007);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (204,'French Guiana','GUF',20,1007);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (205,'Guyana','GUY',20,1007);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (206,'Paraguay','PRY',20,1007);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (207,'Peru','PER',20,1007);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (208,'South Georgia and the South Sandwich Islands','SGS',20,1007);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (209,'Suriname','SUR',20,1007);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (210,'Uruguay','URY',20,1007);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (211,'Venezuela (Bolivarian Republic of)','VEN',20,1007);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (212,'Bermuda','BMU',20,1000);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (213,'Canada','CAN',20,1000);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (214,'Greenland','GRL',20,1000);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (215,'Saint Pierre and Miquelon','SPM',20,1000);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (216,'United States of America','USA',20,1000);

-- ANTARCTICA
--INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (217,Antarctica','ATA',NULL,NULL);
											      
-- ASIA
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (218,'Kazakhstan','KAZ',30,1006);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (219,'Kyrgyzstan','KGZ',30,1006);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (220,'Tajikistan','TJK',30,1006);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (221,'Turkmenistan','TKM',30,1006);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (222,'Uzbekistan','UZB',30,1006);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (223,'China','CHN',30,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (224,'China, Hong Kong Special Administrative Region','HKG',30,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (225,'China, Macao Special Administrative Region','MAC',30,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (226,'Democratic People Republic of Korea','PRK',30,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (227,'Japan','JPN',30,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (228,'Mongolia','MNG',30,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (229,'Republic of Korea','KOR',30,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (230,'Brunei Darussalam','BRN',30,1008);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (231,'Cambodia','KHM',30,1008);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (232,'Indonesia','IDN',30,1008);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (233,'Lao Democratic Republic','LAO',30,1008);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (234,'Malaysia','MYS',30,1008);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (235,'Myanmar','MMR',30,1008);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (236,'Philippines','PHL',30,1008);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (237,'Singapore','SGP',30,1008);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (238,'Thailand','THA',30,1008);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (239,'Timor-Leste','TLS',30,1008);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (240,'Viet Nam','VNM',30,1008);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (241,'Afghanistan','AFG',30,1003);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (242,'Bangladesh','BGD',30,1003);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (243,'Bhutan','BTN',30,1003);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (244,'India','IND',30,1003);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (245,'Iran (Islamic Republic of)','IRN',30,1003);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (246,'Maldives','MDV',30,1003);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (247,'Nepal','NPL',30,1003);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (248,'Pakistan','PAK',30,1003);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (249,'Sri Lanka','LKA',30,1003);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (250,'Armenia','ARM',30,1004);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (251,'Azerbaijan','AZE',30,1004);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (252,'Bahrain','BHR',30,1004);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (253,'Cyprus','CYP',30,1004);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (254,'Georgia','GEO',30,1004);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (255,'Iraq','IRQ',30,1004);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (256,'Israel','ISR',30,1004);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (257,'Jordan','JOR',30,1004);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (258,'Kuwait','KWT',30,1004);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (259,'Lebanon','LBN',30,1004);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (260,'Oman','OMN',30,1004);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (261,'Qatar','QAT',30,1004);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (262,'Saudi Arabia','SAU',30,1004);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (263,'State of Palestine','PSE',30,1004);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (264,'Syrian Arab Republic','SYR',30,1004);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (265,'Türkiye','TUR',30,1004);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (266,'United Arab Emirates','ARE',30,1004);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (267,'Yemen','YEM',30,1004);

-- EUROPE
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (268,'Belarus','BLR',50,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (269,'Bulgaria','BGR',50,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (270,'Czechia','CZE',50,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (271,'Hungary','HUN',50,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (272,'Poland','POL',50,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (273,'Republic of Moldova','MDA',50,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (274,'Romania','ROU',50,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (275,'Russian Federation','RUS',50,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (276,'Slovakia','SVK',50,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (277,'Ukraine','UKR',50,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (278,'Åland Islands','ALA',50,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (279,'Guernsey','GGY',50,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (280,'Jersey','JEY',50,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (281,'Sark','',50,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (282,'Denmark','DNK',50,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (283,'Estonia','EST',50,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (284,'Faroe Islands','FRO',50,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (285,'Finland','FIN',50,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (286,'Iceland','ISL',50,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (287,'Ireland','IRL',50,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (288,'Isle of Man','IMN',50,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (289,'Latvia','LVA',50,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (290,'Lithuania','LTU',50,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (291,'Norway','NOR',50,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (292,'Svalbard and Jan Mayen Islands','SJM',50,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (293,'Sweden','SWE',50,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (294,'United Kingdom of Great Britain and Northern Ireland','GBR',50,1001);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (295,'Albania','ALB',50,1003);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (296,'Andorra','AND',50,1003);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (297,'Bosnia and Herzegovina','BIH',50,1003);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (298,'Croatia','HRV',50,1003);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (299,'Gibraltar','GIB',50,1003);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (300,'Greece','GRC',50,1003);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (301,'Holy See','VAT',50,1003);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (302,'Italy','ITA',50,1003);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (303,'Malta','MLT',50,1003);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (304,'Montenegro','MNE',50,1003);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (305,'North Macedonia','MKD',50,1003);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (306,'Portugal','PRT',50,1003);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (307,'San Marino','SMR',50,1003);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (308,'Serbia','SRB',50,1003);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (309,'Slovenia','SVN',50,1003);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (310,'Spain','ESP',50,1003);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (311,'Austria','AUT',50,1003);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (312,'Belgium','BEL',50,1003);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (313,'France','FRA',50,1003);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (314,'Germany','DEU',50,1003);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (315,'Liechtenstein','LIE',50,1003);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (316,'Luxembourg','LUX',50,1003);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (317,'Monaco','MCO',50,1003);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (318,'Netherlands','NLD',50,1003);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (319,'Switzerland','CHE',50,1003);

-- OCEANIA
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (320,'Australia','AUS',60,1009);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (321,'Christmas Island','CXR',60,1009);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (322,'Cocos (Keeling) Islands','CCK',60,1009);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (323,'Heard Island and McDonald Islands','HMD',60,1009);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (324,'New Zealand','NZL',60,1009);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (325,'Norfolk Island','NFK',60,1009);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (326,'Fiji','FJI',60,1010);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (327,'New Caledonia','NCL',60,1010);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (328,'Papua New Guinea','PNG',60,1010);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (329,'Solomon Islands','SLB',60,1010);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (330,'Vanuatu','VUT',60,1010);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (331,'Guam','GUM',60,1010);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (332,'Kiribati','KIR',60,1010);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (333,'Marshall Islands','MHL',60,1010);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (334,'Micronesia (Federated States of)','FSM',60,1010);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (335,'Nauru','NRU',60,1010);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (336,'Northern Mariana Islands','MNP',60,1010);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (337,'Palau','PLW',60,1010);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (338,'United States Minor Outlying Islands','UMI',60,1010);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (339,'American Samoa','ASM',60,1011);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (340,'Cook Islands','COK',60,1011);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (341,'French Polynesia','PYF',60,1011);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (342,'Niue','NIU',60,1011);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (343,'Pitcairn','PCN',60,1011);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (344,'Samoa','WSM',60,1011);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (345,'Tokelau','TKL',60,1011);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (346,'Tonga','TON',60,1011);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (347,'Tuvalu','TUV',60,1011);
INSERT TABLE LOC.COUNTRIES (COUNTRY_ID,COUNTRY,ISO_ALPHA_CODE,CONTINENT_ID,REGION_ID) VALUES (348,'Wallis and Futuna Islands','WLF',60,1011);
