--- Creat By...: Giovani Pacheco
--- Version....: 1.0
--- Create Date: 11/12/2022
--- Updates....:


---------------------------------------------------------------------------------------------------------
-- Table: STATIES
---------------------------------------------------------------------------------------------------------

CREATE TABLE LOC.STATIES (
  		STATE_ID 		INT NOT NULL, 
		STATE 			VARCHAR2(250), 
		CAPITAL			VARCHAR2(250), 
		ISO_ALPHA_CODE	VARCHAR2(3), 
		REGION_ID 		INT, 
		COUNTRY_ID 		INT
);

--CONSTRAINT

ALTER TABLE LOC.STATIES
	ADD CONSTRAINT PK001_STATIES PRIMARY KEY (STATE_ID);
	
ALTER TABLE LOC.STATIES
	ADD CONSTRAINT FK001_STATIES_TO_COUNTRIES FOREIGN KEY (COUNTRY_ID) REFERENCES LOC.COUNTRIES (COUNTRY_ID);
	
ALTER TABLE LOC.STATIES
	ADD CONSTRAINT FK002_STATIES_TO_REGIONS FOREIGN KEY (REGION_ID) REFERENCES LOC.REGIONS (REGION_ID);


---------------------------------------------------------------------------------------------------------
-- DML: STATIES 
---------------------------------------------------------------------------------------------------------

-- BRAZIL
INSERT INTO LOC.STATIES (STATE_ID,STATE,CAPITAL,ISO_ALPHA_CODE,REGION_ID,COUNTRY_ID) VALUES (1,'Acre','Rio Branco','AC',1012,199);
INSERT INTO LOC.STATIES (STATE_ID,STATE,CAPITAL,ISO_ALPHA_CODE,REGION_ID,COUNTRY_ID) VALUES (2,'Alagoas','Maceió','AL',1014,199);
INSERT INTO LOC.STATIES (STATE_ID,STATE,CAPITAL,ISO_ALPHA_CODE,REGION_ID,COUNTRY_ID) VALUES (3,'Amazonas','Manaus','AM',1012,199);
INSERT INTO LOC.STATIES (STATE_ID,STATE,CAPITAL,ISO_ALPHA_CODE,REGION_ID,COUNTRY_ID) VALUES (4,'Amapá','Macapá','AP',1012,199);
INSERT INTO LOC.STATIES (STATE_ID,STATE,CAPITAL,ISO_ALPHA_CODE,REGION_ID,COUNTRY_ID) VALUES (5,'Bahia','Salvador','BA',1014,199);
INSERT INTO LOC.STATIES (STATE_ID,STATE,CAPITAL,ISO_ALPHA_CODE,REGION_ID,COUNTRY_ID) VALUES (6,'Ceará','Fortaleza','CE',1014,199);
INSERT INTO LOC.STATIES (STATE_ID,STATE,CAPITAL,ISO_ALPHA_CODE,REGION_ID,COUNTRY_ID) VALUES (7,'Distrito Federal','Brasília','DF',1013,199);
INSERT INTO LOC.STATIES (STATE_ID,STATE,CAPITAL,ISO_ALPHA_CODE,REGION_ID,COUNTRY_ID) VALUES (8,'Espírito Santo','Vitória','ES',1008,199);
INSERT INTO LOC.STATIES (STATE_ID,STATE,CAPITAL,ISO_ALPHA_CODE,REGION_ID,COUNTRY_ID) VALUES (9,'Goiás','Goiânia','GO',1013,199);
INSERT INTO LOC.STATIES (STATE_ID,STATE,CAPITAL,ISO_ALPHA_CODE,REGION_ID,COUNTRY_ID) VALUES (10,'Maranhão','São Luís','MA',1014,199);
INSERT INTO LOC.STATIES (STATE_ID,STATE,CAPITAL,ISO_ALPHA_CODE,REGION_ID,COUNTRY_ID) VALUES (11,'Minas Gerais','Belo','MG',1008,199);
INSERT INTO LOC.STATIES (STATE_ID,STATE,CAPITAL,ISO_ALPHA_CODE,REGION_ID,COUNTRY_ID) VALUES (12,'Mato Grosso do Sul','Campo Grande','MS',1013,199);
INSERT INTO LOC.STATIES (STATE_ID,STATE,CAPITAL,ISO_ALPHA_CODE,REGION_ID,COUNTRY_ID) VALUES (13,'Mato Grosso','Cuiabá','MT',1013,199);
INSERT INTO LOC.STATIES (STATE_ID,STATE,CAPITAL,ISO_ALPHA_CODE,REGION_ID,COUNTRY_ID) VALUES (14,'Pará','Belém','PA',1012,199);
INSERT INTO LOC.STATIES (STATE_ID,STATE,CAPITAL,ISO_ALPHA_CODE,REGION_ID,COUNTRY_ID) VALUES (15,'Paraíba','João Pesso','PB',1014,199);
INSERT INTO LOC.STATIES (STATE_ID,STATE,CAPITAL,ISO_ALPHA_CODE,REGION_ID,COUNTRY_ID) VALUES (16,'Pernambuco','Recife','PE',1014,199);
INSERT INTO LOC.STATIES (STATE_ID,STATE,CAPITAL,ISO_ALPHA_CODE,REGION_ID,COUNTRY_ID) VALUES (17,'Piauí','Teresina','PI',1014,199);
INSERT INTO LOC.STATIES (STATE_ID,STATE,CAPITAL,ISO_ALPHA_CODE,REGION_ID,COUNTRY_ID) VALUES (18,'Paraná','Curitiba','PR',1007,199);
INSERT INTO LOC.STATIES (STATE_ID,STATE,CAPITAL,ISO_ALPHA_CODE,REGION_ID,COUNTRY_ID) VALUES (19,'Rio de Janeiro','Rio de Janeiro','RJ',1008,199);
INSERT INTO LOC.STATIES (STATE_ID,STATE,CAPITAL,ISO_ALPHA_CODE,REGION_ID,COUNTRY_ID) VALUES (20,'Rio Grande do Norte','Natal','RN',1014,199);
INSERT INTO LOC.STATIES (STATE_ID,STATE,CAPITAL,ISO_ALPHA_CODE,REGION_ID,COUNTRY_ID) VALUES (21,'Rondônia','Porto Velho','RO',1012,199);
INSERT INTO LOC.STATIES (STATE_ID,STATE,CAPITAL,ISO_ALPHA_CODE,REGION_ID,COUNTRY_ID) VALUES (22,'Roraima','Boa Vista','RR',1012,199);
INSERT INTO LOC.STATIES (STATE_ID,STATE,CAPITAL,ISO_ALPHA_CODE,REGION_ID,COUNTRY_ID) VALUES (23,'Rio Grande do Sul','Porto Alegre','RS',1007,199);
INSERT INTO LOC.STATIES (STATE_ID,STATE,CAPITAL,ISO_ALPHA_CODE,REGION_ID,COUNTRY_ID) VALUES (24,'Santa Catarina','Florianópolis','SC',1007,199);
INSERT INTO LOC.STATIES (STATE_ID,STATE,CAPITAL,ISO_ALPHA_CODE,REGION_ID,COUNTRY_ID) VALUES (25,'Sergipe','Aracaju','SE',1014,199);
INSERT INTO LOC.STATIES (STATE_ID,STATE,CAPITAL,ISO_ALPHA_CODE,REGION_ID,COUNTRY_ID) VALUES (26,'São Paulo','São Paulo','SP',1008,199);
INSERT INTO LOC.STATIES (STATE_ID,STATE,CAPITAL,ISO_ALPHA_CODE,REGION_ID,COUNTRY_ID) VALUES (27,'Tocantins','Palmas','TO',1012,199); 
