--- Creat By...: Giovani Pacheco
--- Version....: 1.0
--- Create Date: 11/12/2022
--- Update.....: 
---         12/11/2022 - Table name change, inclusion of new regions.


---------------------------------------------------------------------------------------------------------
-- Table: REGION
---------------------------------------------------------------------------------------------------------

CREATE TABLE LOC.REGION (
	ID			INT 		NOT NULL, -- IDENTIFICATION KEY
	CONTINENT_ID		INT		NOT NULL, -- FOREING OF TABLE CONTINENTS 
	REGION_NAME		VARCHAR2(50) 	NOT NULL  -- NAME OF REGION
);

--- CONSTRAINTS
ALTER TABLE LOC.REGION 
	ADD CONSTRAINT PK001_SUBREGION PRIMARY KEY (ID);
	
ALTER TABLE LOC.REGION
	ADD CONSTRAINT FK001_SUBRERION_TO_REGION FOREIGN KEY (REGION_ID) REFERENCES LOC.REGION (ID);
	

---------------------------------------------------------------------------------------------------------
-- DML: REGION 
---------------------------------------------------------------------------------------------------------

-- AFRICA
INSERT INTO LOC.REGION (ID,CONTINENT_ID,REGION_NAME) VALUES (10,1,'Northern Africa');
INSERT INTO LOC.REGION (ID,CONTINENT_ID,REGION_NAME) VALUES (20,1,'Sub-Saharan Africa');
INSERT INTO LOC.REGION (ID,CONTINENT_ID,REGION_NAME) VALUES (30,1,'Eastern Africa');
INSERT INTO LOC.REGION (ID,CONTINENT_ID,REGION_NAME) VALUES (40,1,'Middle Africa');
INSERT INTO LOC.REGION (ID,CONTINENT_ID,REGION_NAME) VALUES (50,1,'Southern Africa');
INSERT INTO LOC.REGION (ID,CONTINENT_ID,SUBREGION_NAME) VALUES (60,1,'Western Africa');

-- AMERICAS
INSERT INTO LOC.REGION (ID,CONTINENT_ID,REGION_NAME) VALUES (70,2,'Latin America and the Caribbean');
INSERT INTO LOC.REGION (ID,CONTINENT_ID,REGION_NAME) VALUES (80,2,'Caribbean');
INSERT INTO LOC.REGION (ID,CONTINENT_ID,REGION_NAME) VALUES (90,2,'Central America');
INSERT INTO LOC.REGION (ID,CONTINENT_ID,REGION_NAME) VALUES (100,2,'South America');
INSERT INTO LOC.REGION (ID,CONTINENT_ID,REGION_NAME) VALUES (110,2,'Northern America');

-- ASIA
INSERT INTO LOC.REGION (ID,CONTINENT_ID,REGION_NAME) VALUES (120,4,'Central Asia');
INSERT INTO LOC.REGION (ID,CONTINENT_ID,REGION_NAME) VALUES (130,4,'Eastern Asia');
INSERT INTO LOC.REGION (ID,CONTINENT_ID,REGION_NAME) VALUES (140,4,'South-eastern Asia');
INSERT INTO LOC.REGION (ID,CONTINENT_ID,REGION_NAME) VALUES (150,4,'Southern Asia');
INSERT INTO LOC.REGION (ID,CONTINENT_ID,REGION_NAME) VALUES (160,4,'Western Asia');

-- EUROPA
INSERT INTO LOC.REGION (ID,CONTINENT_ID,REGION_NAME) VALUES (170,5,'Eastern Europe');
INSERT INTO LOC.REGION (ID,CONTINENT_ID,REGION_NAME) VALUES (180,5,'Northern Europe');
INSERT INTO LOC.REGION (ID,CONTINENT_ID,REGION_NAME) VALUES (190,5,'Channel Islands');
INSERT INTO LOC.REGION (ID,CONTINENT_ID,REGION_NAME) VALUES (200,5,'Southern Europe');
INSERT INTO LOC.REGION (ID,CONTINENT_ID,REGION_NAME) VALUES (210,5,'Western Europe');

-- OCEANIA
INSERT INTO LOC.REGION (ID,CONTINENT_ID,REGION_NAME) VALUES (220,6,'Australia and New Zealand');
INSERT INTO LOC.REGION (ID,CONTINENT_ID,REGION_NAME) VALUES (230,6,'Melanesia');
INSERT INTO LOC.REGION (ID,CONTINENT_ID,REGION_NAME) VALUES (240,6,'Micronesia');
INSERT INTO LOC.REGION (ID,CONTINENT_ID,REGION_NAME) VALUES (250,6,'Polynesia');

-- ANTARCTICA
INSERT INTO LOC.REGION (ID,CONTINENT_ID,REGION_NAME) VALUES (260,3,'Antarctica');

-- OTHERS
INSERT INTO LOC.REGION (ID,CONTINENT_ID,REGION_NAME) VALUES (270,7,'North');
INSERT INTO LOC.REGION (ID,CONTINENT_ID,REGION_NAME) VALUES (280,7,'North East');
INSERT INTO LOC.REGION (ID,CONTINENT_ID,REGION_NAME) VALUES (290,7,'Midwest');
INSERT INTO LOC.REGION (ID,CONTINENT_ID,REGION_NAME) VALUES (300,7,'Southeast');
INSERT INTO LOC.REGION (ID,CONTINENT_ID,REGION_NAME) VALUES (310,7,'South');
