--- Creat By...: Giovani Pacheco
--- Version....: 1.0
--- Create Date: 11/12/2022
--- Description:
---         -- 12/11/2022 - Inclusion of the "Capital" column and update of the load script with the new values and the USA status base.


---------------------------------------------------------------------------------------------------------
-- Table: STATIES
---------------------------------------------------------------------------------------------------------


CREATE TABLE LOC.STATIES (
	ID			INT 		NOT NULL,
	CONTRY_ID		INT		NOT NULL,
	STATE_NAME		VARCHAR2(250)	NOT NULL,
	CAPITAL			VARCHAR2(250)	NOT NULL,
	ALPHA_CODE		VARCHAR2(5)
);

--- CONSTRAINT
ALTER TABLE LOC.STATIES
  ADD CONSTRAINT PK001_STATIES PRIMARY KEY (ID);
		
ALTER TABLE LOC.STATIES
  ADD CONSTRAINT FK001_STATIES_TO_COUNTRIES FOREIGN KEY (CONTRY_ID) REFERENCES LOC.COUNTRIES (ID);
	

---------------------------------------------------------------------------------------------------------
-- DML: STATIES 
---------------------------------------------------------------------------------------------------------

-- BRAZIL
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,ALPHA_CODE) VALUES (1,102,'Acre','Rio Branco','AC');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,ALPHA_CODE) VALUES (2,102,'Alagoas','Maceió','AL');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,ALPHA_CODE) VALUES (3,102,'Amazonas','Manaus','AM');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,ALPHA_CODE) VALUES (4,102,'Amapá','Macapá','AP');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,ALPHA_CODE) VALUES (5,102,'Bahia','Salvador','BA');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,ALPHA_CODE) VALUES (6,102,'Ceará','Fortaleza','CE');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,ALPHA_CODE) VALUES (7,102,'Distrito Federal','Brasília','DF');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,ALPHA_CODE) VALUES (8,102,'Espírito Santo','Vitória','ES');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,ALPHA_CODE) VALUES (9,102,'Goiás','Goiânia','GO');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,ALPHA_CODE) VALUES (10,102,'Maranhão','São Luís','MA');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,ALPHA_CODE) VALUES (11,102,'Minas Gerais','Belo Horizonte','MG');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,ALPHA_CODE) VALUES (12,102,'Mato Grosso do Sul','Campo Grande','MS');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,ALPHA_CODE) VALUES (13,102,'Mato Grosso','Cuiabá','MT');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,ALPHA_CODE) VALUES (14,102,'Pará','Belém','PA');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,ALPHA_CODE) VALUES (15,102,'Paraíba','João Pessoa','PB');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,ALPHA_CODE) VALUES (16,102,'Pernambuco','Recife','PE');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,ALPHA_CODE) VALUES (17,102,'Piauí','Teresina','PI');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,ALPHA_CODE) VALUES (18,102,'Paraná','Curitiba','PR');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,ALPHA_CODE) VALUES (19,102,'Rio de Janeiro','Rio de Janeiro','RJ');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,ALPHA_CODE) VALUES (20,102,'Rio Grande do Norte','Natal','RN');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,ALPHA_CODE) VALUES (21,102,'Rondônia','Porto Velho','RO');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,ALPHA_CODE) VALUES (22,102,'Roraima','Boa Vista','RR');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,ALPHA_CODE) VALUES (23,102,'Rio Grande do Sul','Porto Alegre','RS');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,ALPHA_CODE) VALUES (24,102,'Santa Catarina','Florianópolis','SC');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,ALPHA_CODE) VALUES (25,102,'Sergipe','Aracaju','SE');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,ALPHA_CODE) VALUES (26,102,'São Paulo','São Paulo','SP');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,ALPHA_CODE) VALUES (27,102,'Tocantins','Palmas','TO');

-- USA
