--- Creat By...: Giovani Pacheco
--- Version....: 1.0
--- Create Date: 11/12/2022
--- Description: 



---------------------------------------------------------------------------------------------------------
-- Table: SUBREGION
---------------------------------------------------------------------------------------------------------

CREATE TABLE LOC.SUBREGION (
	ID					INT 		NOT NULL, -- IDENTIFICATION KEY
	REGION_ID				INT		NOT NULL, -- FOREING OF TABLE REGION 
	SUBREGION_NAME				VARCHAR2(50) 	NOT NULL  -- NAME OF SUBREGION
);

--- CONSTRAINTS
ALTER TABLE LOC.SUBREGION 
	ADD CONSTRAINT PK001_SUBREGION PRIMARY KEY (ID);
	
ALTER TABLE LOC.SUBREGION
	ADD CONSTRAINT FK001_SUBRERION_TO_REGION FOREIGN KEY (REGION_ID) REFERENCES LOC.REGION (ID);
	

---------------------------------------------------------------------------------------------------------
-- DML: SUBREGION 
---------------------------------------------------------------------------------------------------------

-- AFRICA
INSERT INTO LOC.SUBREGION (ID,REGION_ID,SUBREGION_NAME) VALUES (10,1,'Northern Africa');
INSERT INTO LOC.SUBREGION (ID,REGION_ID,SUBREGION_NAME) VALUES (20,1,'Sub-Saharan Africa');
INSERT INTO LOC.SUBREGION (ID,REGION_ID,SUBREGION_NAME) VALUES (30,1,'Eastern Africa');
INSERT INTO LOC.SUBREGION (ID,REGION_ID,SUBREGION_NAME) VALUES (40,1,'Middle Africa');
INSERT INTO LOC.SUBREGION (ID,REGION_ID,SUBREGION_NAME) VALUES (50,1,'Southern Africa');
INSERT INTO LOC.SUBREGION (ID,REGION_ID,SUBREGION_NAME) VALUES (60,1,'Western Africa');

-- AMERICAS
INSERT INTO LOC.SUBREGION (ID,REGION_ID,SUBREGION_NAME) VALUES (70,2,'Latin America and the Caribbean');
INSERT INTO LOC.SUBREGION (ID,REGION_ID,SUBREGION_NAME) VALUES (80,2,'Caribbean');
INSERT INTO LOC.SUBREGION (ID,REGION_ID,SUBREGION_NAME) VALUES (90,2,'Central America');
INSERT INTO LOC.SUBREGION (ID,REGION_ID,SUBREGION_NAME) VALUES (100,2,'South America');
INSERT INTO LOC.SUBREGION (ID,REGION_ID,SUBREGION_NAME) VALUES (110,2,'Northern America');

-- ASIA
INSERT INTO LOC.SUBREGION (ID,REGION_ID,SUBREGION_NAME) VALUES (120,4,'Central Asia');
INSERT INTO LOC.SUBREGION (ID,REGION_ID,SUBREGION_NAME) VALUES (130,4,'Eastern Asia');
INSERT INTO LOC.SUBREGION (ID,REGION_ID,SUBREGION_NAME) VALUES (140,4,'South-eastern Asia');
INSERT INTO LOC.SUBREGION (ID,REGION_ID,SUBREGION_NAME) VALUES (150,4,'Southern Asia');
INSERT INTO LOC.SUBREGION (ID,REGION_ID,SUBREGION_NAME) VALUES (160,4,'Western Asia');

-- EUROPA
INSERT INTO LOC.SUBREGION (ID,REGION_ID,SUBREGION_NAME) VALUES (170,5,'Eastern Europe');
INSERT INTO LOC.SUBREGION (ID,REGION_ID,SUBREGION_NAME) VALUES (180,5,'Northern Europe');
INSERT INTO LOC.SUBREGION (ID,REGION_ID,SUBREGION_NAME) VALUES (190,5,'Channel Islands');
INSERT INTO LOC.SUBREGION (ID,REGION_ID,SUBREGION_NAME) VALUES (200,5,'Southern Europe');
INSERT INTO LOC.SUBREGION (ID,REGION_ID,SUBREGION_NAME) VALUES (210,5,'Western Europe');

-- OCEANIA
INSERT INTO LOC.SUBREGION (ID,REGION_ID,SUBREGION_NAME) VALUES (220,6,'Australia and New Zealand');
INSERT INTO LOC.SUBREGION (ID,REGION_ID,SUBREGION_NAME) VALUES (230,6,'Melanesia');
INSERT INTO LOC.SUBREGION (ID,REGION_ID,SUBREGION_NAME) VALUES (240,6,'Micronesia');
INSERT INTO LOC.SUBREGION (ID,REGION_ID,SUBREGION_NAME) VALUES (250,6,'Polynesia');

-- ANTARCTICA
INSERT INTO LOC.SUBREGION (ID,REGION_ID,SUBREGION_NAME) VALUES (260,3,'Antarctica');
