--- Creat By...: Giovani Pacheco
--- Version....: 1.0
--- Create Date: 11/12/2022
--- Description:


---------------------------------------------------------------------------------------------------------
-- Table: COUNTRIES
---------------------------------------------------------------------------------------------------------


CREATE TABLE LOC.COUNTRIES (
	ID				INT NOT NULL,
	SUBREGION_ID			INT NOT NULL,
	COUNTRY_NAME			VARCHAR2(250) NOT NULL,
	ISO_ALPHA_CODE			VARCHAR2(3)
);

--- CONSTRAINTS
ALTER TABLE LOC.COUNTRIES
	ADD CONSTRAINT PK001_COUNTRIES PRIMARY KEY (ID);

ALTER TABLE LOC.COUNTRIES
	ADD CONSTRAINT FK001_COUNTRIES_TO_SUBREGION FOREIGN KEY (SUBREGION_ID) REFERENCES LOC.SUBREGION (ID);
	
	


INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (1,10,'Algeria','DZA');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (2,10,'Antarctica','ATA');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (3,10,'Egypt','EGY');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (4,10,'Libya','LBY');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (5,10,'Morocco','MAR');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (6,10,'Sudan','SDN');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (7,10,'Tunisia','TUN');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (8,10,'Western Sahara','ESH');
										  
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (9,20,'British Indian Ocean Territory','IOT');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (10,20,'Burundi','BDI');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (11,20,'Comoros','COM');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (12,20,'Djibouti','DJI');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (13,20,'Eritrea','ERI');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (14,20,'Ethiopia','ETH');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (15,20,'French Southern Territories','ATF');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (16,20,'Kenya','KEN');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (17,20,'Madagascar','MDG');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (18,20,'Malawi','MWI');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (19,20,'Mauritius','MUS');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (20,20,'Mayotte','MYT');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (21,20,'Mozambique','MOZ');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (22,20,'Réunion','REU');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (23,20,'Rwanda','RWA');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (24,20,'Seychelles','SYC');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (25,20,'Somalia','SOM');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (26,20,'South Sudan','SSD');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (27,20,'Uganda','UGA');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (28,20,'United Republic of Tanzania','TZA');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (29,20,'Zambia','ZMB');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (30,20,'Zimbabwe','ZWE');
										 
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (31,30,'Angola','AGO');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (32,30,'Cameroon','CMR');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (33,30,'Central African Republic','CAF');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (34,30,'Chad','TCD');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (35,30,'Congo','COG');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (36,30,'Democratic Republic of the Congo','COD');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (37,30,'Equatorial Guinea','GNQ');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (38,30,'Gabon','GAB');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (39,30,'Sao Tome and Principe','STP');
										  
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (40,40,'Botswana','BWA');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (41,40,'Eswatini','SWZ');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (42,40,'Lesotho','LSO');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (43,40,'Namibia','NAM');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (44,40,'South Africa','ZAF');
										  
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (45,50,'Armenia','ARM');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (46,50,'Azerbaijan','AZE');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (47,50,'Bahrain','BHR');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (48,50,'Cyprus','CYP');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (49,50,'Georgia','GEO');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (50,50,'Iraq','IRQ');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (51,50,'Israel','ISR');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (52,50,'Jordan','JOR');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (53,50,'Kuwait','KWT');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (54,50,'Lebanon','LBN');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (55,50,'Oman','OMN');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (56,50,'Qatar','QAT');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (57,50,'Saudi Arabia','SAU');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (58,50,'State of Palestine','PSE');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (59,50,'Syrian Arab Republic','SYR');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (60,50,'Turkey','TUR');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (61,50,'United Arab Emirates','ARE');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (62,50,'Yemen','YEM');
										  
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (63,60,'Anguilla','AIA');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (64,60,'Antigua and Barbuda','ATG');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (65,60,'Aruba','ABW');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (66,60,'Bahamas','BHS');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (67,60,'Barbados','BRB');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (68,60,'Bonaire, Sint Eustatius and Saba','BES');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (69,60,'British Virgin Islands','VGB');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (70,60,'Cayman Islands','CYM');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (71,60,'Cuba','CUB');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (72,60,'Curaçao','CUW');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (73,60,'Dominica','DMA');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (74,60,'Dominican Republic','DOM');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (75,60,'Grenada','GRD');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (76,60,'Guadeloupe','GLP');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (77,60,'Haiti','HTI');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (78,60,'Jamaica','JAM');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (79,60,'Martinique','MTQ');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (80,60,'Montserrat','MSR');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (81,60,'Puerto Rico','PRI');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (82,60,'Saint Barthélemy','BLM');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (83,60,'Saint Kitts and Nevis','KNA');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (84,60,'Saint Lucia','LCA');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (85,60,'Saint Martin (French Part)','MAF');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (86,60,'Saint Vincent and the Grenadines','VCT');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (87,60,'Sint Maarten (Dutch part)','SXM');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (88,60,'Trinidad and Tobago','TTO');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (89,60,'Turks and Caicos Islands','TCA');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (90,60,'United States Virgin Islands','VIR');
										   
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (91,70,'Belize','BLZ');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (92,70,'Costa Rica','CRI');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (93,70,'El Salvador','SLV');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (94,70,'Guatemala','GTM');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (95,70,'Honduras','HND');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (96,70,'Mexico','MEX');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (97,70,'Nicaragua','NIC');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (98,70,'Panama','PAN');
										  
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (99,80,'Argentina','ARG');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (100,80,'Bolivia (Plurinational State of)','BOL');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (101,80,'Bouvet Island','BVT');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (102,80,'Brazil','BRA');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (103,80,'Chile','CHL');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (104,80,'Colombia','COL');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (105,80,'Ecuador','ECU');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (106,80,'Falkland Islands (Malvinas)','FLK');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (107,80,'French Guiana','GUF');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (108,80,'Guyana','GUY');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (109,80,'Paraguay','PRY');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (110,80,'Peru','PER');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (111,80,'South Georgia and the South Sandwich Islands','SGS');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (112,80,'Suriname','SUR');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (113,80,'Uruguay','URY');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (114,80,'Venezuela (Bolivarian Republic of)','VEN');
										   
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (115,90,'Bermuda','BMU');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (116,90,'Canada','CAN');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (117,90,'Greenland','GRL');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (118,90,'Saint Pierre and Miquelon','SPM');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (119,90,'United States of America','USA');

INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (120,100,'Kazakhstan','KAZ');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (121,100,'Kyrgyzstan','KGZ');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (122,100,'Tajikistan','TJK');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (123,100,'Turkmenistan','TKM');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (124,100,'Uzbekistan','UZB');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (125,110,'China','CHN');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (126,110,'China, Hong Kong Special Administrative Region','HKG');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (127,110,'China, Macao Special Administrative Region','MAC');
--INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (128,110,'Democratic People's Republic of Korea','PRK');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (129,110,'Japan','JPN');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (130,110,'Mongolia','MNG');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (131,110,'Republic of Korea','KOR');

INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (132,120,'Brunei Darussalam','BRN');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (133,120,'Cambodia','KHM');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (134,120,'Indonesia','IDN');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE)  VALUES (135,120,'''Lao People''s Democratic Republic''', 'LAO')

INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (136,120,'Malaysia','MYS');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (137,120,'Myanmar','MMR');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (138,120,'Philippines','PHL');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (139,120,'Singapore','SGP');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (140,120,'Thailand','THA');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (141,120,'Timor-Leste','TLS');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (142,120,'Viet Nam','VNM');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (143,130,'Afghanistan','AFG');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (144,130,'Bangladesh','BGD');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (145,130,'Bhutan','BTN');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (146,130,'India','IND');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (147,130,'Iran (Islamic Republic of)','IRN');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (148,130,'Maldives','MDV');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (149,130,'Nepal','NPL');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (150,130,'Pakistan','PAK');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (151,130,'Sri Lanka','LKA');

INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (152,150,'Belarus','BLR');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (153,150,'Bulgaria','BGR');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (154,150,'Czechia','CZE');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (155,150,'Hungary','HUN');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (156,150,'Poland','POL');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (157,150,'Republic of Moldova','MDA');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (158,150,'Romania','ROU');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (159,150,'Russian Federation','RUS');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (160,150,'Slovakia','SVK');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (161,150,'Ukraine','UKR');

INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (162,160,'Åland Islands','ALA');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (163,160,'Denmark','DNK');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (164,160,'Estonia','EST');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (165,160,'Faroe Islands','FRO');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (166,160,'Finland','FIN');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (167,160,'Guernsey','GGY');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (168,160,'Iceland','ISL');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (169,160,'Ireland','IRL');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (170,160,'Isle of Man','IMN');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (171,160,'Jersey','JEY');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (172,160,'Latvia','LVA');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (173,160,'Lithuania','LTU');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (174,160,'Norway','NOR');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (175,160,'Sark','');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (176,160,'Svalbard and Jan Mayen Islands','SJM');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (177,160,'Sweden','SWE');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (178,160,'United Kingdom of Great Britain and Northern Ireland','GBR');

INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (179,170,'Albania','ALB');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (180,170,'Andorra','AND');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (181,170,'Bosnia and Herzegovina','BIH');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (182,170,'Croatia','HRV');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (183,170,'Gibraltar','GIB');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (184,170,'Greece','GRC');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (185,170,'Holy See','VAT');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (186,170,'Italy','ITA');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (187,170,'Malta','MLT');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (188,170,'Montenegro','MNE');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (189,170,'North Macedonia','MKD');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (190,170,'Portugal','PRT');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (191,170,'San Marino','SMR');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (192,170,'Serbia','SRB');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (193,170,'Slovenia','SVN');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (194,170,'Spain','ESP');

INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (195,180,'Austria','AUT');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (196,180,'Belgium','BEL');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (197,180,'Benin','BEN');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (198,180,'Burkina Faso','BFA');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (199,180,'Cabo Verde','CPV');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (200,180,'Côte d’Ivoire','CIV');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (201,180,'France','FRA');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (202,180,'Gambia','GMB');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (203,180,'Germany','DEU');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (204,180,'Ghana','GHA');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (205,180,'Guinea','GIN');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (206,180,'Guinea-Bissau','GNB');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (207,180,'Liberia','LBR');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (208,180,'Liechtenstein','LIE');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (209,180,'Luxembourg','LUX');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (210,180,'Mali','MLI');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (211,180,'Mauritania','MRT');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (212,180,'Monaco','MCO');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (213,180,'Netherlands','NLD');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (214,180,'Niger','NER');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (215,180,'Nigeria','NGA');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (216,180,'Saint Helena','SHN');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (217,180,'Senegal','SEN');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (218,180,'Sierra Leone','SLE');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (219,180,'Switzerland','CHE');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (220,180,'Togo','TGO');

INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (221,190,'Australia','AUS');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (222,190,'Christmas Island','CXR');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (223,190,'Cocos (Keeling) Islands','CCK');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (224,190,'Heard Island and McDonald Islands','HMD');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (225,190,'New Zealand','NZL');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (226,190,'Norfolk Island','NFK');

INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (227,200,'Fiji','FJI');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (228,200,'New Caledonia','NCL');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (229,200,'Papua New Guinea','PNG');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (230,200,'Solomon Islands','SLB');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (231,200,'Vanuatu','VUT');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (232,210,'Guam','GUM');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (233,210,'Kiribati','KIR');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (234,210,'Marshall Islands','MHL');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (235,210,'Micronesia (Federated States of)','FSM');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (236,210,'Nauru','NRU');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (237,210,'Northern Mariana Islands','MNP');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (238,210,'Palau','PLW');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (239,210,'United States Minor Outlying Islands','UMI');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (240,220,'American Samoa','ASM');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (241,220,'Cook Islands','COK');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (242,220,'French Polynesia','PYF');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (243,220,'Niue','NIU');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (244,220,'Pitcairn','PCN');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (245,220,'Samoa','WSM');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (246,220,'Tokelau','TKL');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (247,220,'Tonga','TON');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (248,220,'Tuvalu','TUV');
INSERT INTO LOC.COUNTRIES (ID,SUBREGION_ID,COUNTRY_NAME,ISO_ALPHA_CODE ) VALUES (249,220,'Wallis and Futuna Islands','WLF');
