--- Creat By...: Giovani Pacheco
--- Version....: 1.0
--- Create Date: 11/12/2022
--- Description:
---         -- 12/11/2022 - Inclusion of the "Capital" column and update of the load script with the new values and the USA status base.


---------------------------------------------------------------------------------------------------------
-- Table: STATIES
---------------------------------------------------------------------------------------------------------


CREATE TABLE LOC.STATIES (
	ID			INT 		NOT NULL,
	CONTRY_ID		INT		NOT NULL,
	STATE_NAME		VARCHAR2(250)	NOT NULL,
	CAPITAL			VARCHAR2(250)	NOT NULL,
	REGION_ID		INT,
	ALPHA_CODE		VARCHAR2(5)
);

--- CONSTRAINT
ALTER TABLE LOC.STATIES
  ADD CONSTRAINT PK001_STATIES PRIMARY KEY (ID);
		
ALTER TABLE LOC.STATIES
  ADD CONSTRAINT FK001_STATIES_TO_COUNTRIES FOREIGN KEY (CONTRY_ID) REFERENCES LOC.COUNTRIES (ID);
  
ALTER TABLE LOC.STATIES
  ADD CONSTRAINT FK002_STATIES_TO_REGIONS FOREIGN KEY (REGION_ID) REFERENCES LOC.REGIONS (ID);

---------------------------------------------------------------------------------------------------------
-- DML: STATIES 
---------------------------------------------------------------------------------------------------------

-- BRAZIL
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (1,102,'Acre','Rio Branco',270,'AC');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (2,102,'Alagoas','Maceió',280,'AL');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (3,102,'Amazonas','Manaus',270,'AM');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (4,102,'Amapá','Macapá',270,'AP');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (5,102,'Bahia','Salvador',280,'BA');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (6,102,'Ceará','Fortaleza',280,'CE');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (7,102,'Distrito Federal',290,'Brasília','DF');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (8,102,'Espírito Santo',300,'Vitória','ES');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (9,102,'Goiás','Goiânia',290,'GO');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (10,102,'Maranhão','São Luís',280,'MA');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (11,102,'Minas Gerais','Belo Horizonte',300,'MG');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (12,102,'Mato Grosso do Sul','Campo Grande',290,'MS');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (13,102,'Mato Grosso','Cuiabá',290,'MT');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (14,102,'Pará','Belém',270,'PA');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (15,102,'Paraíba','João Pessoa',280,'PB');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (16,102,'Pernambuco','Recife',280,'PE');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (17,102,'Piauí','Teresina',280,'PI');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (18,102,'Paraná','Curitiba',310,'PR');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (19,102,'Rio de Janeiro','Rio de Janeiro',300,'RJ');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (20,102,'Rio Grande do Norte','Natal',280,'RN');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (21,102,'Rondônia','Porto Velho',270,'RO');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (22,102,'Roraima','Boa Vista',270,'RR');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (23,102,'Rio Grande do Sul','Porto Alegre',310,'RS');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (24,102,'Santa Catarina','Florianópolis',310,'SC');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (25,102,'Sergipe','Aracaju',280,'SE');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (26,102,'São Paulo','São Paulo',300,'SP');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (27,102,'Tocantins','Palmas',270,'TO');

-- USA
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (1,119,'Alabama','Montgomery',300,'AL');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (2,119,'Alaska','Juneau',320,'AK');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (3,119,'Arizona','Phoenix',330,'AZ');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (4,119,'Arkansas','Little Rock',300,'AR');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (5,119,'California','Sacramento',320,'CA');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (6,119,'Carolina del Norte','Raleigh',300,'NC');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (7,119,'Carolina del Sur','Columbia',300,'SC');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (8,119,'Colorado','Denver',320,'CO');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (9,119,'Connecticut','Hartford',280,'CT');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (10,119,'Dakota del Norte','Bismarck',290,'ND');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (11,119,'Dakota del Sur ','Pierre',290,'SD');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (12,119,'Delaware','Dover',280,'DE');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (13,119,'Florida','Tallahassee',300,'FL');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (14,119,'Georgia','Atlanta',300,'GA');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (15,119,'Hawái','Honolulu',320,'HI');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (16,119,'Idaho','Boise',320,'ID');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (17,119,'Illinois','Springfield',290,'IL');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (18,119,'Indiana','Indianápolis',290,'IN');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (19,119,'Iowa','Des Moines',290,'IA');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (20,119,'Kansas','Topeka',290,'KS');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (21,119,'Kentucky','Frankfort',300,'KY');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (22,119,'Luisiana','Baton Rouge',300,'LA');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (23,119,'Maine','Augusta',280,'ME');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (24,119,'Maryland','Annapolis',280,'MD');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (25,119,'Massachusetts','Boston',280,'MA');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (26,119,'Míchigan','Lansing',290,'MI');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (27,119,'Minnesota','Saint Paul',290,'MN');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (28,119,'Misisipi','Jackson',300,'MS');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (29,119,'Misuri','Jefferson City',290,'MO');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (30,119,'Montana','Helena',320,'MT');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (31,119,'Nebraska','Lincoln',290,'NE');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (32,119,'Nevada','Carson City',320,'NV');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (33,119,'Nueva Jersey','Trenton',280,'NJ');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (34,119,'Nueva York','Albany',280,'NY');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (35,119,'Nuevo Hampshire','Concord',280,'NH');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (36,119,'Nuevo México','Santa Fe',330,'NM');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (37,119,'Ohio','Columbus',290,'OH');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (38,119,'Oklahoma','Oklahoma City',330,'OK');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (39,119,'Oregón','Salem',320,'OR');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (40,119,'Pensilvania','Harrisburg',280,'PA');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (41,119,'Rhode Island','Providence',280,'RI');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (42,119,'Tennessee','Nashville',300,'TN');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (43,119,'Texas','Austin',330,'TX');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (44,119,'Utah','Salt Lake City',320,'UT');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (45,119,'Vermont','Montpelier',280,'VT');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (46,119,'Virginia','Richmond',300,'VA');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (47,119,'Virginia Occidental','Charleston',300,'WV');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (48,119,'Washington','Olympia',320,'WA');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (49,119,'Wisconsin','Madison',290,'WI');
INSERT INTO LOC.STATIES (ID,CONTRY_ID,STATE_NAME,CAPITAL,REGION_ID,ALPHA_CODE) VALUES (50,119,'Wyoming ','Cheyenne',320,'WY');
